name = "api"
main = "src/server/worker.ts"
compatibility_date = "2025-10-25"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "TAB_OVERFLOW_KV"
id = "ba2c9eb2462342939acc6135b9c80a2f"

[triggers]
crons = ["0 * * * *"]

[env.production]

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true