name: Deploy client to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  VITE_BACKEND_URL: https://fxn-m-api.fxn-m.workers.dev
  VITE_POSTHOG_KEY: ${{ secrets.VITE_POSTHOG_KEY }}
  VITE_POSTHOG_HOST: ${{ secrets.VITE_POSTHOG_HOST }}
  VITE_POSTHOG_CAPTURE_DEV: "false"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Install dependencies
        run: bun ci
      - name: Build
        run: bun run build
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
